package io.github.tavstaldev.openChat;

import io.github.tavstaldev.minecorelib.config.ConfigurationBase;

import java.util.HashMap;
import java.util.Map;

public class OpenChatConfiguration extends ConfigurationBase {

    public OpenChatConfiguration() {
        super(OpenChat.Instance, "config.yml", null);
    }

    @Override
    protected void loadDefaults() {
        // General
        resolve("locale", "hun");
        resolve("usePlayerLocale", true);
        resolve("checkForUpdates", true);
        resolve("debug", false);
        resolve("prefix", "&bOpen&3Chat &8»");

        // Anti-Spam
        resolve("antiSpam.enabled", true);
        resolve("antiSpam.chatDelay", 2);
        resolve("antiSpam.commandDelay", 2);
        resolve("antiSpam.maxDuplicates", 2);
        resolve("antiSpam.executeCommand", new String[] { "kick {player} Please do not spam" });
        resolve("antiSpam.exemptPermission", "openchat.bypass.antispam");

        // Anti-Advertisement
        resolve("antiAdvertisement.enabled", true);
        resolve("antiAdvertisement.regex", "(?i)\\b((?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]|\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|\\b(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\\.)+(?:[a-z]{2,}))\\b");
        resolve("antiAdvertisement.whitelist", new String[]{
                "mestermc.hu",
                "discord.gg/mestermc",
                "youtube.com/mestermc",
                "facebook.com/mestermc",
                "tiktok.com/@mestermc"
        });
        resolve("antiAdvertisement.executeCommand", new String[] { "kick {player} Please do not spam" });
        resolve("antiAdvertisement.exemptPermission", "openchat.bypass.antiadvertisement");

        // Anti-Caps
        resolve("antiCaps.enabled", true);
        resolve("antiCaps.minLength", 10);
        resolve("antiCaps.percentage", 70);
        resolve("antiCaps.exemptPermission", "openchat.bypass.anticaps");
        resolve("antiCaps.executeCommand", new String[] { "kick {player} Please do not spam" });

        // Anto-swear
        resolve("antiSwear.enabled", true);
        Map<Character, String> characterMappings = new HashMap<>();
        characterMappings.put('a', "[aA@4]");
        characterMappings.put('e', "[eE3]");
        characterMappings.put('i', "[iI1!íÍ]");
        characterMappings.put('o', "[oO0óÓ]");
        characterMappings.put('s', "[sS5$]");
        characterMappings.put('u', "[uUúÚ]");
        characterMappings.put('ü', "[üÜűŰuU]");
        characterMappings.put('t', "[tT7+]");
        characterMappings.put('g', "[gG9]");
        characterMappings.put('b', "[bB8]");
        characterMappings.put('z', "[zZ2]");
        resolve("antiSwear.characterMapping", characterMappings);
        //#region Swear words
        resolve("antiSwear.swearWords", new String[]{
                "ass",
                "asshole",
                "bitch",
                "bastard",
                "cunt",
                "damn",
                "dick",
                "fuck",
                "hell",
                "piss",
                "pussy",
                "retard",
                "shit",
                "slut",
                "twat",
                "whore",
                "chink",
                "dyke",
                "fag",
                "faggot",
                "gook",
                "kike",
                "nigger",
                "spic",
                "tranny",
                "wetback",
                "blowjob",
                "cock",
                "ejaculate",
                "jerkoff",
                "masturbate",
                "orgasm",
                "penis",
                "semen",
                "vagina",
                "aids-es",
                "agyatlan",
                "agybatetovált",
                "agyfasz",
                "agyhalott",
                "agyonkúrt",
                "agyonvert",
                "agyrákos",
                "animalsex-mániás",
                "antibaro",
                "anyadat",
                "anyatokkal",
                "aprófaszú",
                "arcbarakott",
                "aszaltfaszú",
                "átbaszott",
                "ágybavizelős",
                "balfasz",
                "balfészek",
                "baromfifasz",
                "basz-o-matic",
                "baszál",
                "baszad",
                "baszhatatlan",
                "baszlak",
                "basznivaló",
                "basszál",
                "basszodj",
                "bebaszott",
                "befosi",
                "békapicsa",
                "bélböfi",
                "beleiből kiforgatott",
                "bélszél",
                "bronz térdű",
                "brunya",
                "büdös szájú",
                "büdösszájú",
                "búvalbaszott",
                "buzeráns",
                "buzernyák",
                "buzi",
                "buzikurva",
                "cafat",
                "cafka",
                "céda",
                "cérnafaszú",
                "cigány",
                "cici",
                "cottonfej",
                "cornhub",
                "csaf",
                "cseszett",
                "csibefasz",
                "csicska",
                "csipszar",
                "csirkefaszú",
                "csitri",
                "csöcs",
                "csöcsfej",
                "csöppszar",
                "csöves",
                "csupaszfarkú",
                "cuncipunci",
                "deformáltfaszú",
                "dekorált pofájú",
                "degenerált",
                "dobseggű",
                "döbbenetesen segg",
                "drogos",
                "drogozni",
                "drugs",
                "drug",
                "dughatatlan",
                "dunyhavalagú",
                "duplafaszú",
                "ebfasz",
                "eki",
                "ekidzseki",
                "elbaszott",
                "eleve hülye",
                "extrahülye",
                "fafogú rézfűrésszel megsebzett",
                "fasszopó",
                "fasz",
                "fasz-emulátor",
                "faszagyú",
                "faszarc",
                "faszfej",
                "faszfészek",
                "faszkalap",
                "faszk-arika",
                "faszkedvelő",
                "faszkópé",
                "faszogány",
                "faszpörgettyű",
                "faszsapka",
                "faszszagú",
                "fasztalan",
                "fasztarisznya",
                "fasztengely",
                "fasztolvaj",
                "faszváladék",
                "faszverő",
                "félrebaszott",
                "félrefingott",
                "félreszart",
                "félribanc",
                "féreg",
                "fing",
                "fityma",
                "fölcsinált",
                "fölfingott",
                "fos",
                "foskemence",
                "fospisztoly",
                "fospumpa",
                "fostalicska",
                "fütyi",
                "fütyinyalogató",
                "fütykös",
                "geci",
                "gecinyelő",
                "geciszaró",
                "geciszívó",
                "genny",
                "gennyesszájú",
                "gennygóc",
                "genyac",
                "genyó",
                "gerinctelen",
                "gólyafos",
                "görbefaszú",
                "gyennyszopó",
                "gyíkfing",
                "hájpacni",
                "halj éhen",
                "halj ki",
                "halj meg",
                "hatalmas nagy fasz",
                "hátbabaszott",
                "házikurva",
                "hererákos",
                "hígagyú",
                "hihetetlenül fasz",
                "hikomat",
                "hímnőstény",
                "hímringyó",
                "hímvesző",
                "hímveszővel",
                "hiperstrici",
                "hitler",
                "hitler-imádó",
                "hitlerista",
                "hivatásos balfasz",
                "hú de segg",
                "hugyagyú",
                "hugyos",
                "hugytócsa",
                "hüje",
                "hülye",
                "hülyécske",
                "hülyegyerek",
                "idióta",
                "inkubátor-szökevény",
                "integrált barom",
                "ionizált faszú",
                "iq bajnok",
                "iq fighter",
                "iq hiányos",
                "irdatlanul köcsög",
                "íveltfaszú",
                "jajj de barom",
                "joint",
                "jókora fasz",
                "kaka",
                "kakamatyi",
                "kaki",
                "kaksi",
                "kecskebaszó",
                "kellően fasz",
                "képlékeny faszú",
                "keresve sem található fasz",
                "kétfaszú",
                "kétszer agyonbaszott",
                "keys",
                "ki-bebaszott",
                "kibaszott",
                "kifingott",
                "kiherélt",
                "kikakkantott",
                "kikészült",
                "kimagaslóan fasz",
                "kimondhatatlan pöcs",
                "kis szaros",
                "kisfütyi",
                "kill yourself",
                "klotyószagú",
                "kokain",
                "ködmönbe bújtatott",
                "koj",
                "kopárfaszú",
                "korlátolt gecizésű",
                "kotonszökevény",
                "középszar",
                "köcsög",
                "kretén",
                "kuki",
                "kula",
                "kunkorított faszú",
                "kurva",
                "kurvaanyjú",
                "kurvapecér",
                "kurlak",
                "kutyakaki",
                "kutyapina",
                "kutyaszar",
                "lankadtfaszú",
                "lebaszirgált",
                "lebaszott",
                "lecseszett",
                "leírhatatlanul segg",
                "lemenstruált",
                "leokádott",
                "lepkefing",
                "leprafészek",
                "leszart",
                "leszbikus",
                "lőcs",
                "lőcsgéza",
                "lófasz",
                "lógócsöcsű",
                "lóhugy",
                "lotyó",
                "lucskos",
                "lugnya",
                "lyukasbelű",
                "lyukasfaszú",
                "lyukát vakaró",
                "lyuktalanított",
                "mamutsegg",
                "mangalica",
                "marihuana",
                "marihónaja",
                "maszturbációs görcs",
                "maszturbagép",
                "maszturbáltatott",
                "megbaszlak",
                "megfingatott",
                "megkettyintett",
                "megkúrt",
                "megkurlak",
                "megszopatott",
                "mesterséges faszú",
                "metamphetamine",
                "méteres kékeres",
                "meth",
                "mikrotökű",
                "mocsok",
                "mocskod",
                "mocskos",
                "mojfing",
                "műfaszú",
                "muff",
                "multifasz",
                "műtöttpofájú",
                "náci",
                "nagymellek",
                "nagyfejű",
                "nikotinpatkány",
                "nimfomániás",
                "nuna",
                "nunci",
                "nuncóka",
                "nyalábfasz",
                "nyalj ki",
                "nyalj meg",
                "nyelestojás",
                "nyomorék",
                "nyúlszar",
                "oltári nagy fasz",
                "ondónyelő",
                "orbitálisan hülye",
                "ordenálé",
                "összebaszott",
                "ötcsillagos fasz",
                "ótvaros",
                "óvszerezett",
                "pénisz",
                "peremesfaszú",
                "picsa",
                "picsafej",
                "picsameresztő",
                "picsánnyalt",
                "picsánrugott",
                "picsányi",
                "pikkelypáncélt hordó",
                "pina",
                "pinés",
                "pinuja",
                "pisa",
                "pisaszagú",
                "pisis",
                "pöcs",
                "pöcsfej",
                "porbafingó",
                "porno",
                "pornó",
                "pornóbuzi",
                "pornómániás",
                "poresz",
                "pudvás",
                "pudváslikú",
                "puhafaszú",
                "punci",
                "puncimókus",
                "puncis",
                "punciutáló",
                "puncivirág",
                "puresz",
                "qtyaszar",
                "qki",
                "qrva",
                "rákos",
                "rák a beled",
                "rabló",
                "rágcsáltfaszú",
                "redva",
                "rendkívül fasz",
                "repedtsarkú",
                "retek",
                "retkes",
                "rétó-román",
                "rézhasú",
                "ribanc",
                "riherongy",
                "ritka fogú",
                "rivalizáló",
                "rohadj",
                "rojtospicsájú",
                "rongyospinájú",
                "roppant hülye",
                "rossz kurva",
                "rosszlányok",
                "rószlányok",
                "rosszlanyok",
                "rőfös fasz",
                "saját nemével kefélő",
                "segg",
                "seggarc",
                "seggdugó",
                "seggfej",
                "seggnyaló",
                "seggszőr",
                "seggtorlasz",
                "sikoltozásokba öltöztetett",
                "strici",
                "suttyó",
                "sutyerák",
                "szálkafaszú",
                "szar",
                "szaralak",
                "szarbojler",
                "szarcsimbók",
                "szarevő",
                "szarfaszú",
                "szarházi",
                "szarjankó",
                "szarnivaló",
                "szarosvalagú",
                "szarrá vágott",
                "szarrágó",
                "szarszagú",
                "szarszájú",
                "szartragacs",
                "szarzsák",
                "szárazfing",
                "szégyencsicska",
                "szifiliszes",
                "szivattyús kurva",
                "szop-o-matic",
                "szopás",
                "szopd",
                "szopi le",
                "szopj",
                "szopógép",
                "szopógörcs",
                "szopós kurva",
                "szopottfarkú",
                "szófosó",
                "szokatlanul fasz",
                "szuperbuzi",
                "szuperkurva",
                "szűklyukú",
                "szultán udvarát megjárt",
                "szúnyogfaszni",
                "szűzhártya-repedéses",
                "szűzkurva",
                "szűzpicsa",
                "szűzpunci",
                "tetves",
                "tikfos",
                "tikszar",
                "tompátökű",
                "toszatlan",
                "toszott",
                "totálisan hülye",
                "törpefaszú",
                "tyúkfasznyi",
                "tyúkszar",
                "tyű de picsa",
                "vadfasz",
                "valag",
                "valagváladék",
                "végbélféreg",
                "xar",
                "xvideos",
                "xxx",
                "zsíragy",
                "zsugorított faszú"
        });
        //#endregion
        resolve("antiSwear.exemptPermission", "openchat.bypass.antiswear");
        resolve("antiSwear.executeCommand", new String[] { "kick {player} Please do not spam" });
    }
}
